from collections import OrderedDict

TEST_PAIRED_SICK_HEALTHY = OrderedDict({'BRCA': tuple(('/cs/cbio/tommy/TCGA/BRCA_Primary_Tumor.tsv.gz',
                                                       '/cs/cbio/tommy/TCGA/BRCA_Solid_Tissue_Normal.tsv.gz'))})

test_paths_sick = ['/cs/cbio/tommy/TCGA//BRCA_Primary_Tumor.chr19.tsv.gz']
test_paths_normal = ['/cs/cbio/tommy/TCGA//BRCA_Solid_Tissue_Normal.chr19.tsv.gz']
test_label_dict = OrderedDict({1: tuple(('BRCA', True)),
                               2: tuple(('BRCA', False))})

LABELS_DICT_SUBTYPE = OrderedDict({1: tuple(('BRCA', True)),
                                   2: tuple(('LUAD', True)),
                                   3: tuple(('LUSC', True)),
                                   4: tuple(('COAD', True)),
                                   5: tuple(('KIRP', True)),
                                   6: tuple(('LIHC', True)),
                                   7: tuple(('PRAD', True)),
                                   8: tuple(('THCA', True)),
                                   9: tuple(('HNSC', True)),
                                   10: tuple(('UCEC', True)),
                                   11: tuple(('KIRC', True)),
                                   12: tuple(('BRCA', False)),
                                   13: tuple(('LUAD', False)),
                                   14: tuple(('LUSC', False)),
                                   15: tuple(('COAD', False)),
                                   16: tuple(('KIRP', False)),
                                   17: tuple(('LIHC', False)),
                                   18: tuple(('PRAD', False)),
                                   19: tuple(('THCA', False)),
                                   20: tuple(('HNSC', False)),
                                   21: tuple(('UCEC', False)),
                                   22: tuple(('KIRC', False))})

PATHS_SICK_SUBTYPE = ['/cs/cbio/tommy/TCGA//BRCA_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/LUAD_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/LUSC_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/COAD_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/KIRP_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/LIHC_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/PRAD_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/THCA_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/HNSC_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/UCEC_Primary_Tumor.tsv.gz',
                      '/cs/cbio/tommy/TCGA/KIRC_Primary_Tumor.tsv.gz']

PATHS_NORMAL_SUBTYPE = ['/cs/cbio/tommy/TCGA/BRCA_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/LUAD_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/LUSC_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/COAD_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/KIRP_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/LIHC_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/PRAD_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/THCA_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/HNSC_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/UCEC_Solid_Tissue_Normal.tsv.gz',
                        '/cs/cbio/tommy/TCGA/KIRC_Solid_Tissue_Normal.tsv.gz']

LABELS_DICT = OrderedDict({1: tuple(('BRCA', True)),
                           2: tuple(('LUAD', True)),
                           3: tuple(('LUSC', True)),
                           4: tuple(('COAD', True)),
                           5: tuple(('KIRP', True)),
                           6: tuple(('LIHC', True)),
                           7: tuple(('PRAD', True)),
                           8: tuple(('THCA', True)),
                           9: tuple(('HNSC', True)),
                           10: tuple(('UCEC', True)),
                           11: tuple(('KIRC', True)),
                           12: tuple(('ESCA', True)),
                           13: tuple(('PAAD', True)),
                           14: tuple(('STAD', True)),
                           15: tuple(('OV', True)),
                           16: tuple(('BLCA', True)),
                           17: tuple(('CESC', True)),
                           18: tuple(('GBM', True)),
                           19: tuple(('LC', True)),
                           20: tuple(('PCPG', True)),
                           21: tuple(('READ', True)),
                           22: tuple(('SARC', True)),
                           23: tuple(('SKCM', True)),
                           24: tuple(('THYM', True)),
                           25: tuple(('ACC', True)),
                           26: tuple(('DLBC', True)),
                           27: tuple(('KICH', True)),
                           28: tuple(('LGG', True)),
                           29: tuple(('MESO', True)),
                           30: tuple(('TGCT', True)),
                           31: tuple(('UCS', True)),
                           32: tuple(('UVM', True)),
                           33: tuple(('BRCA', False)),
                           33: tuple(('LUAD', False)),
                           35: tuple(('LUSC', False)),
                           36: tuple(('COAD', False)),
                           37: tuple(('KIRP', False)),
                           38: tuple(('LIHC', False)),
                           39: tuple(('PRAD', False)),
                           40: tuple(('THCA', False)),
                           41: tuple(('HNSC', False)),
                           42: tuple(('UCEC', False)),
                           43: tuple(('KIRC', False)),
                           44: tuple(('ESCA', False)),
                           45: tuple(('PAAD', False)),
                           46: tuple(('STAD', False)),
                           47: tuple(('OV', False)),
                           48: tuple(('BLCA', False)),
                           49: tuple(('CESC', False)),
                           50: tuple(('GBM', False)),
                           51: tuple(('LC', False)),
                           52: tuple(('PCPG', False)),
                           53: tuple(('READ', False)),
                           54: tuple(('SARC', False)),
                           55: tuple(('SKCM', False)),
                           56: tuple(('THYM', False))})

PATHS_SICK = ['/cs/cbio/tommy/TCGA/BRCA_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/LUAD_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/LUSC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/COAD_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/KIRP_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/LIHC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/PRAD_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/THCA_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/HNSC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/UCEC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/KIRC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/ESCA_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/PAAD_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/STAD_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/OV_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/BLCA_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/CESC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/GBM_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/LC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/PCPG_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/READ_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/SARC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/SKCM_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/THYM_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/ACC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/DLBC_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/KICH_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/LGG_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/MESO_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/TGCT_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/UCS_Primary_Tumor.tsv.gz',
              '/cs/cbio/tommy/TCGA/UVM_Primary_Tumor.tsv.gz']

PATHS_NORMAL = ['/cs/cbio/tommy/TCGA/BRCA_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/LUAD_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/LUSC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/COAD_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/KIRP_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/LIHC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/PRAD_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/THCA_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/HNSC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/UCEC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/KIRC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/ESCA_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/PAAD_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/STAD_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/OV_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/BLCA_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/CESC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/GBM_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/LC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/PCPG_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/READ_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/SARC_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/SKCM_Solid_Tissue_Normal.tsv.gz',
                '/cs/cbio/tommy/TCGA/THYM_Solid_Tissue_Normal.tsv.gz']

PAIRED_SICK_HEALTHY = OrderedDict([('BRCA', tuple(('/cs/cbio/tommy/TCGA//BRCA_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/BRCA_Solid_Tissue_Normal.tsv.gz'))),
                                   ('LUAD', tuple(('/cs/cbio/tommy/TCGA/LUAD_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/LUAD_Solid_Tissue_Normal.tsv.gz'))),
                                   ('LUSC', tuple(('/cs/cbio/tommy/TCGA/LUSC_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/LUSC_Solid_Tissue_Normal.tsv.gz'))),
                                   ('COAD', tuple(('/cs/cbio/tommy/TCGA/COAD_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/COAD_Solid_Tissue_Normal.tsv.gz'))),
                                   ('KIRP', tuple(('/cs/cbio/tommy/TCGA/KIRP_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/KIRP_Solid_Tissue_Normal.tsv.gz'))),
                                   ('LIHC', tuple(('/cs/cbio/tommy/TCGA/LIHC_Primary_Tumor.tsv.gz',  '/cs/cbio/tommy/TCGA/LIHC_Solid_Tissue_Normal.tsv.gz'))),
                                   ('PRAD', tuple(('/cs/cbio/tommy/TCGA/PRAD_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/PRAD_Solid_Tissue_Normal.tsv.gz'))),
                                   ('THCA', tuple(('/cs/cbio/tommy/TCGA/THCA_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/THCA_Solid_Tissue_Normal.tsv.gz'))),
                                   ('HNSC', tuple(('/cs/cbio/tommy/TCGA/HNSC_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/HNSC_Solid_Tissue_Normal.tsv.gz'))),
                                   ('UCEC', tuple(('/cs/cbio/tommy/TCGA/UCEC_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/UCEC_Solid_Tissue_Normal.tsv.gz'))),
                                   ('KIRC', tuple(('/cs/cbio/tommy/TCGA/KIRC_Primary_Tumor.tsv.gz', '/cs/cbio/tommy/TCGA/KIRC_Solid_Tissue_Normal.tsv.gz')))])

#TODO create df of tissue, sick/normal, path, index, is_sub_type, num_patients
